name: Application Build and Test

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies for GenericWebApi
        run: dotnet restore src/api/GenericWebApi/GenericWebApi.csproj
      - name: Build GenericWebApi
        run: dotnet build --no-restore src/api/GenericWebApi/GenericWebApi.csproj

      - name: Run Unit Tests
        run: dotnet test --logger "trx;LogFileName=test-results.trx" src/api/BusinessLogic.Tests/BusinessLogic.Tests.csproj
      - name: Unit Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: GenericWebApi Unit Tests
          path: src/api/BusinessLogic.Tests/TestResults/test-results.trx
          reporter: dotnet-trx

      - name: Run Integration Tests
        run: dotnet test --logger "trx;LogFileName=test-results.trx" src/api/GenericWebApi.IntegrationTests/GenericWebApi.IntegrationTests.csproj
      - name: Integration Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: GenericWebApi Unit Tests
          path: src/api/BusinessLogic.Tests/TestResults/test-results.trx
          reporter: dotnet-trx
